### ISSUE TITLE
joinLines() using \r\n instead of \n

### ISSUE THREAD

**Issue by Jimmerz28** [pedsmoreira/battlecry#11]
Currently `joinLines()` adds `\r\n` to the end of each line, which isn't really optimal as some environments lint to ensure line endings are only `\n`.

It would be best if `joinLines()` either used `[os.EOL](https://nodejs.org/api/os.html#os_os_eol)` or offered  an option via config of which line endings we wanted battlecry to use when writing/appending to files.

**Comment by pedsmoreira** [comment]
👍, would you like to give it a shot and open a PR?

**Comment by pedsmoreira** [comment]
Closing this issue, as it was fixed by your PR #12
