### ISSUE TITLE
Babel Unknown plugin

### ISSUE THREAD

**Issue by SeanLatimer** [pedsmoreira/battlecry#3]
After installing in my project, I get this error whenever I attempt to run the CLI.
Complains about `babel-plugin-transform-async-to-generator` being an unknown plugin.

[![asciicast](https://asciinema.org/a/9ZyeRj7DjfKhJWvPbfAdnBPhk.png)](https://asciinema.org/a/9ZyeRj7DjfKhJWvPbfAdnBPhk)

**Comment by pedsmoreira** [comment]
Hi @SeanLatimer, thanks for taking the time to report the issue.

I double checked and `battlecry`, as of this version, needs to be installed globally.

The package resolution used with babel is quite tricky in this case, as the packages are inside `battlecry` and not on your project itself.

If you want to create a PR for this issue, please feel free to do so.
